name: iTouch Grade Checker

on:
  schedule:
    - cron: '0 * * * *' # 每小時自動執行一次
  workflow_dispatch:      # 允許手動點擊執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Grade Scraper
        env:
          STUDENT_ID: ${{ secrets.STUDENT_ID }}
          STUDENT_PW: ${{ secrets.STUDENT_PW }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python grade.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add graded_count.txt || exit 0
          git commit -m "Update graded count" || exit 0
          git push
